version: 2.1
  jobs:
    build:
       docker:
        - image: circleci/node:16.1
      steps:
        - checkout
        - run:
        - name: "installing dependices"
        - command:
            npm install
    build_docker_image:
        docker:
         - image: circleci/node16.1
        steps:
         - checkout  
         - setup_remote_docker
           docker_layer_caching:false
         - run:
             name: build image
             command: docker build --name ci -t latest .
                     


