version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.1
    steps:
      - checkout
      - run:
          name: "installing dependencies"
          command: npm install
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: false
      - run:
          name: build image
          command: docker build -t latest .
